# 服务环境配置
spring:
  # 部署环境 dev 开发环境|test 测试环境|pro 部署生产环境
  profiles:
    active: mysql
  #编码格式
  http:
    encoding:
      charset: utf8
  #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #上传文件配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 2000
    #password: asam@123123
    password:
    jedis:
      pool:
        max-active: 32  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 200 # 最大空闲连接数
        min-idle: 4  #最小空闲连接数
    lettuce:
      max-active: 32  #连接池最大连接数(使用负值表示没有限制) 默认为8
      max-idle: 200 # 最大空闲连接数
      min-idle: 4  #最小空闲连接数
      max-wait: 10 #连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#-----------------------------------------------------------------------------------------------------------------------
#mybatis配置
mybatis-plus:
  configuration:
    # 是否开启， A_COLUMN（下划线命名）议不开启，原因：数据库字段与实体字段一致性原则
    call-setters-on-nulls: true # 返回map时true: 到 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true     #建当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml,classpath:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
#-----------------------------------------------------------------------------------------------------------------------
# 日志配置
logging:
  config: classpath:logback-spring.xml