# 服务环境配置
spring:
  datasource:
    dynamic:
      primary: service_user
      datasource:
        service_user:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.13.41:33086/mes_product_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: root
#          password: admin
          password: admin2015
      durid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
#-----------------------------------------------------------------------------------------------------------------------
#mybatis配置
mybatis-plus:
  #数据库大写下划线转换
  #capital-mode: true
  global-config:
    db-config:
      id-type: auto   #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      field-strategy: NOT_EMPTY   #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      db-type: MYSQL  #数据库类型