spring:
  profiles:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接办公室服务器数据库
    url: jdbc:mysql://192.168.13.228:3306/robot_core?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    #连接国产化服务器需要加上useSSL=false
    #连接本地服务器地址
    #url: jdbc:mysql://192.168.13.228:3306/robot_core?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    #连接MariaDB
    #url: jdbc:mysql://192.168.13.228:3306/robot_core?useUnicode=true&characterEncoding=utf8mb4&useSSL=false
    username: root    #asam
    password: admin
#    password: admin2015
    #password: ZqDfJYWsh7Q=
    #type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        # 取消小驼峰到下划线映射(加上这个)
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
#-----------------------------------------------------------------------------------------------------------------------
#实体映射参网址--->     https://gitee.com/sunchenbin/mybatis-enhance
#actable,mybatis
actable:
  table:
    auto: update
  #create	系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
  #update	系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
  #none 		系统不做任何处理。
  #add		新增表/新增字段/新增索引/新增唯一约束的功能，不做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
  model:
    pack: com.robotCore.*.entity #扫描用于创建表的对象的包名，多个包用“,”隔开
  database:
    type: mysql #数据库类型 目前只支持mysql
# mybatis-plus配置
mybatis-plus:
  #数据库大写下划线转换
  #capital-mode: true
  global-config:
    db-config:
      id-type: auto   #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      field-strategy: NOT_EMPTY   #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      db-type: MYSQL  #数据库类型MYSQL、DM